VendaDeAutomoveis/Controllers/VendaController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using VendaDeAutomoveis.Entidades;
using VendaDeAutomoveis.Filters;
using VendaDeAutomoveis.Models;
using VendaDeAutomoveis.Repository;
using static VendaDeAutomoveis.Entidades.Cliente;
using static VendaDeAutomoveis.Entidades.Venda;

namespace VendaDeAutomoveis.Controllers
{
    [AutorizacaoFilter]
    public class VendaController : Controller
    {
        private ClienteRepository clienteRepository;
        private VendaRepository vendaRepository;
        private VeiculoRepository veiculoRepository;
        private FormaPagamentoRepository formaPagamentoRepository;
        private EnderecoRepository enderecoRepository;

        public VendaController(VendaRepository vendaRepository, ClienteRepository clienteRepository, VeiculoRepository veiculoRepository, FormaPagamentoRepository formaPagamentoRepository, EnderecoRepository enderecoRepository)
        {
            this.clienteRepository = clienteRepository;
            this.vendaRepository = vendaRepository;
            this.veiculoRepository = veiculoRepository;
            this.formaPagamentoRepository = formaPagamentoRepository;
            this.enderecoRepository = enderecoRepository;
        }

        public ActionResult FormularioCadastro()
        {
            ViewBag.Cliente = clienteRepository.ObterTodos();
            ViewBag.Veiculo = veiculoRepository.ObterTodos();
            ViewBag.FormaDePagamento = formaPagamentoRepository.ObterTodos();   
            return View();
        }
        public ActionResult AdicionarVenda(Venda venda)
        {
            ViewBag.Cliente = clienteRepository.ObterTodos();
            ViewBag.Veiculo = veiculoRepository.ObterTodos();

            if (ModelState.IsValid)
            {
                FormaDePagamento formaDePagamento = formaPagamentoRepository.ObterPorId(venda.IdFormaDePagamento);
                Cliente cliente = clienteRepository.ObterPorId(venda.IdCliente);

                if (venda.TipoEntrega == 0)
                {
                    ModelState.AddModelError("TipoEntrega", "Escolha um tipo de Entrega!");
                    return View("FormularioCadastro", venda);
                }
                if (venda.TipoEntrega == Entrega.Domiciliar && cliente.Endereco == null || venda.TipoEntrega == Entrega.Domiciliar && cliente.Endereco.Numero == null
                    || venda.TipoEntrega == Entrega.Domiciliar && cliente.Endereco.Estado == null || venda.TipoEntrega == Entrega.Domiciliar && cliente.Endereco.Cidade == null
                    || venda.TipoEntrega == Entrega.Domiciliar && cliente.Endereco.CEP == null)
                {

                    ModelState.AddModelError("TipoEntrega", " Para concluir a compra informe seu endereço na tela de clientes");
                    ViewBag.Cliente = clienteRepository.ObterTodos();
                    ViewBag.Veiculo = clienteRepository.ObterTodos();
                    ViewBag.ExibirCampo = true;
                    return View("FormularioCadastro", venda);
                }

                vendaRepository.Adicionar(venda);
                MudarClienteComunParaVip(cliente);
                Veiculo veiculo = veiculoRepository.ObterPorId(venda.Id);
                AumentarValorVeiculoEsportivo(venda);
                CalcularPagamento(venda);
                return RedirectToAction("Index");
            }
            else
            {
                return View("FormularioCadastro");
            }
        }

        public ActionResult Index()
        {
            IList<Venda> vendas = vendaRepository.ObterTodos();
            return View(vendas);
        }

        public ActionResult HistoricoPedidos(HistoricoPedidosModel model)
        {
            model.Clientes = clienteRepository.ObterTodos();
            model.Vendas = vendaRepository.BuscarPorCliente(model.IdCliente);
            return View(model);
        }

        private void MudarClienteComunParaVip(Cliente cliente)
        {
            //if (cliente.TipoDoCliente == TipoCliente.Comum && vendaRepository.TotalPorCliente(cliente.IdCliente) >= 200000)
            //{
            //    cliente.TipoDoCliente = TipoCliente.Vip;
            //    clienteRepository.Editar(cliente);
            //}
        }

        private decimal AumentarValorVeiculoEsportivo(Venda venda)
        {
            if (venda.Veiculo.TipoVeiculo == VeiculoTipo.Esportivo)
            {
                string recebendoObservacao = venda.Observacoes;
                venda.Valor = (venda.Valor + 12000);
                venda.Observacoes = recebendoObservacao + " / Veiculo Esportivo : Acréscimo de R$12.000,00 referente ao período de 12 meses de seguro obrigatório";
                vendaRepository.Editar(venda);
            }
            return venda.Valor;
        }

        private decimal CalcularPagamento(Venda venda)
        {
            string recebendoObservacao = venda.Observacoes;

            if (venda.FormaDePagamento.ModeloFormaDePagamento == ModelosDePagamento.PagamentoAVista.ToString())
            {
                venda.Observacoes = recebendoObservacao + " Financiamento com pagamento à vista";
            }
            else if (venda.FormaDePagamento.ModeloFormaDePagamento == ModelosDePagamento.PagamentoAPrazo12xComJuros.ToString())
            {
                decimal parcela = venda.Valor;
                parcela = parcela / 12;
                venda.Observacoes = recebendoObservacao + " Parcelas :" + parcela.ToString("c") + " /mês";
            }
            else if (venda.FormaDePagamento.ModeloFormaDePagamento == ModelosDePagamento.PagamentoAPrazo12xSemJuros.ToString())
            {
                decimal parcela = venda.Valor;
                parcela = parcela / 60;
                venda.Observacoes = recebendoObservacao + " Parcelas :" + parcela.ToString("c") + " /mês";
            }
            else if (venda.FormaDePagamento.ModeloFormaDePagamento == ModelosDePagamento.PagamentoAPrazo60xComJuros.ToString())
            {
                double juros = 0.03;
                venda.Valor = (venda.Valor * Convert.ToDecimal(juros)) + venda.Valor;
                decimal parcela = venda.Valor;
                parcela = parcela / 12;
                venda.Observacoes = recebendoObservacao + " Parcelas :" + parcela.ToString("c") + " /mês";
            }
            else if (venda.FormaDePagamento.ModeloFormaDePagamento == ModelosDePagamento.PagamentoAPrazo60xSemJuros.ToString())
            {
                double juros = 0.05;
                venda.Valor = (venda.Valor * Convert.ToDecimal(juros)) + venda.Valor;
                decimal parcela = venda.Valor;
                parcela = parcela / 60;
                venda.Observacoes = recebendoObservacao + " Parcelas :" + parcela.ToString("c") + " /mês";
            }
            vendaRepository.Editar(venda);

            return venda.Valor;
        }

        public ActionResult PegarPrecoProduto(Guid id)
        {
            var produto = veiculoRepository.ObterPorId(id);
            return Content(produto.Valor.ToString());
        }

        public ActionResult PegarFormaDePagamento(Guid IdCliente)
        {
            var cliente = clienteRepository.ObterPorId(IdCliente);

            IList<FormaDePagamento> formasPagamentos = new List<FormaDePagamento>();

            if (cliente.TipoDoCliente == TipoCliente.Vip)
            {
                formasPagamentos = formaPagamentoRepository.ObterListarFormaPagamentoVip();
            }
            else
            {
                formasPagamentos = formaPagamentoRepository.ObterFormaPagamentoComum();
            }

            return PartialView("_ParcialViewFormaDePagamento", formasPagamentos);
        }

        public ActionResult PegarEndereco(Guid idCliente)
        {
            var clienteEndereco = enderecoRepository.PegarEnderencoPorIdCliente(idCliente);
            return PartialView("_ParcialviewEndereco", clienteEndereco);
        }

        public ActionResult AtualizarEnderecos(Guid idCliente, string Endereco, string Bairro, string NumeroDaCasa, string CEP, string Cidade, string Estado, string Complemento)
        {

            if (ModelState.IsValid)
            {
                var endereco = enderecoRepository.PegarEnderencoPorIdCliente(idCliente);

                endereco.EnderecoNome = Endereco;
                endereco.Bairro = Bairro;
                endereco.Numero = NumeroDaCasa;
                endereco.CEP = CEP;
                endereco.Cidade = Cidade;
                endereco.Estado = Estado;
                endereco.Complemento = Complemento;

                enderecoRepository.EditarEndereco(endereco);

                return null;
            }
            else
            {
                return Content("Campo errado");
            }
        }
    }
}

VendaDeAutomoveis/Views/Venda/EditarClienteParcial.cshtml
@model VendaDeAutomoveis.Entidades.Venda

@using (Html.BeginForm("EditarClientes", "Venda", FormMethod.Post))
{
    @Html.HiddenFor(u => u.IdCliente, new { @class = "form-control" })

    @Html.LabelFor(u => u.Cliente.Nome, "Nome")
    @Html.TextBoxFor(u => u.Cliente.Nome, new { @class = "form-control" })

    <br />

    @Html.LabelFor(u => u.Cliente.RG, "RG")
    @Html.TextBoxFor(u => u.Cliente.RG, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.Cliente.RG)

    <br />

    @Html.LabelFor(u => u.Cliente.CPF, "CPF/MF")
    @Html.TextBoxFor(u => u.Cliente.CPF, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.Cliente.CPF)

    <br />

    @Html.LabelFor(u => u.Cliente.TipoDoCliente, "Tipo do cliente")
    @Html.EnumDropDownListFor(m => m.Cliente.TipoDoCliente, "Tipo do Cliente", new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.Cliente.TipoDoCliente)

    <br />

    @Html.LabelFor(u => u.Cliente.DataNascimento, "Data de Nascimento")
    @Html.TextBoxFor(u => u.Cliente.DataNascimento, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.Cliente.DataNascimento)

    <br />

    @Html.LabelFor(u => u.Cliente.Endereco, "Endereço")
    @Html.TextBoxFor(u => u.Cliente.Endereco, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.Cliente.Endereco)

    <br />

    @Html.LabelFor(u => u.Cliente.Endereco.Numero, "Número da casa")
    @Html.TextBoxFor(u => u.Cliente.Endereco.Numero, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.Cliente.Endereco.Numero)

    <br />

    @Html.LabelFor(u => u.Cliente.Endereco.Complemento, "Complemento")
    @Html.TextBoxFor(u => u.Cliente.Endereco.Complemento, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.Cliente.Endereco.Complemento)

    <br />

    @Html.LabelFor(u => u.Cliente.Endereco.CEP, "CEP")
    @Html.TextBoxFor(u => u.Cliente.Endereco.CEP, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.Cliente.Endereco.CEP)

    <br />

    @Html.LabelFor(u => u.Cliente.Endereco.Bairro, "Bairro")
    @Html.TextBoxFor(u => u.Cliente.Endereco.Bairro, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.Cliente.Endereco.Bairro)

    <br />

    @Html.LabelFor(u => u.Cliente.Endereco.Cidade, "Cidade")
    @Html.TextBoxFor(u => u.Cliente.Endereco.Cidade, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.Cliente.Endereco.Cidade)

    <br />

    @Html.LabelFor(u => u.Cliente.Endereco.Estado, "Estado")
    @Html.TextBoxFor(u => u.Cliente.Endereco.Estado, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.Cliente.Endereco.Estado)

    <br />

    @Html.LabelFor(u => u.Cliente.Email, "E-mail")
    @Html.TextBoxFor(u => u.Cliente.Email, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.Cliente.Email)

    <br />

    <input type="submit" value="Salvar" />

}

VendaDeAutomoveis/Views/Venda/FormularioCadastro.cshtml
@model VendaDeAutomoveis.Entidades.Venda

<br />
<br />
<br />
<br />

@using (Html.BeginForm("AdicionarVenda", "Venda", FormMethod.Post))
{

    @Html.LabelFor(m => m.IdCliente, "Nome do Cliente*")
    @Html.DropDownListFor(m => m.IdCliente,
        new SelectList(ViewBag.Cliente, "IdCliente", "Nome"), "Nome do Cliente",
        new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m.IdCliente)

    <br />

    @Html.LabelFor(m => m.IdProduto, "Modelo do Produto*")
    @Html.DropDownListFor(m => m.Veiculo.Id,
        new SelectList(ViewBag.Veiculo, "IdProduto", "ModeloVeiculo"), "Modelo do Produto",
            new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m.IdProduto)

    <br />

    @Html.LabelFor(m => m.Valor, "Valor da Compra*")
    @Html.TextBoxFor(m => m.Valor, new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m.Valor)

    <br />

    <div id="ViewParcialFormaDePagamento">

    </div>

    <br />

    @Html.LabelFor(m => m.TipoEntrega, "Tipo de Entrega*")
    @Html.EnumDropDownListFor(m => m.TipoEntrega, "Tipo de Entrega", new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m.TipoEntrega)

    <br />

    <div id="viewParcialEndereco">

    </div>

    <br />
    @Html.LabelFor(m => m.Observacoes, "Observação*")
    @Html.TextBoxFor(m => m.Observacoes, new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m.Observacoes)

    <br />

    <input type="submit" value="Vender" />

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.maskedinput.min.js"></script>

    <script type="text/javascript">

        $(function () {

            @if (ViewBag.ExibirCampo != null)
                {
                    @:PegarvalorEnderecoAjax();
                                                            }

            $("#IdProduto").change(function () {

                PegarvalorVeiculoAjax();
            });

            //$("#IdCliente").change(function () {

            //    PegarvalorEnderecoAjax();
            //});

            $("#TipoEntrega").change(function () {

                PegarvalorEnderecoAjax();

            });

            $("#IdCliente").change(function () {
                PegarvalorEnderecoAjax();
                PegarFormaDePagamento();

            });
        });


        function PegarvalorVeiculoAjax() {
            $.ajax({
                url: '@Url.Action("PegarPrecoProduto")',
                type: "post",
                dataType: "html",
                data: { IdProduto: $("#IdProduto").val() },

                success: function (data) {

                    $("#Valor").val(data);

                }
            });
        }

        function PegarvalorEnderecoAjax() {
          
            if ($("#IdCliente").val() != '' && $("#TipoEntrega").val() == 2) {
                $('#viewParcialEndereco').hide();
            }

            if ($("#IdCliente").val() != '' && $("#TipoEntrega").val() == 1) {
                $('#viewParcialEndereco').show();

                $.ajax({
                    url: '@Url.Action("PegarEndereco")',
                    type: "post",
                    dataType: "html",
                    data: { IdCliente: $("#IdCliente").val() },

                    success: function (data) {
                        $('#viewParcialEndereco').html(data);
                        $("#atualizar").click(function () {

                            AtualizarEnderecoAjax()
                        });
                    }
                });
            }

        }


        function AtualizarEnderecoAjax() {

            $.ajax({
                url: '@Url.Action("AtualizarEnderecos")',
                type: "post",
                dataType: "html",
                data: {
                    IdCliente: $("#IdCliente").val(),
                    Endereco: $("#Endereco").val(),
                    Bairro: $("#Bairro").val(),
                    NumeroDaCasa: $("#NumeroDaCasa").val(),
                    CEP: $("#CEP").val(),
                    Cidade: $("#Cidade").val(),
                    Estado: $("#Estado").val(),
                    Complemento: $("#Complemento").val()

                },

                success: function (data) {

                    alert("Endereço Alterado");

                }
            });
        }

        function PegarFormaDePagamento() {

            $.ajax({
                url: '@Url.Action("PegarFormaDePagamento")', //Metodo da minha controller
                type: "post",
                dataType: "html",
                data: { IdCliente: $("#IdCliente").val() },

                success: function (data) {

                    $('#ViewParcialFormaDePagamento').html(data); //div para renderizar

                }
            });
        }

    </script>
}

VendaDeAutomoveis/Views/Venda/HistoricoPedidos.cshtml
@model  VendaDeAutomoveis.Models.HistoricoPedidosModel

<br />
<br />
<br />
<br />
<br />
<br />

@using (Html.BeginForm("HistoricoPedidos", "Venda", FormMethod.Get))
{
    @Html.LabelFor(m => m.IdCliente, "Cliente")
    @Html.DropDownListFor(m => m.IdCliente,
        new SelectList(Model.Clientes, "IdCliente", "Nome"),
        "Escolha um Cliente")

    <input type="submit" value="Buscar" />
}

<table class="table table-hover">
    <thead>
        <tr>  
            <th>Modelo do Veículo</th>
            <th>Tipo do Veículo</th>
            <th>Valor do Veículo</th>
            <th>Tipo de Entrega</th>
            <th>Forma de Pagamento</th>
            <th>Observação</th>
        </tr>
</thead>
    <tbody>
        @foreach (var m in Model.Vendas)
        {
            <tr>
                <td>@m.Veiculo.ModeloVeiculo</td>
                <td>@m.Veiculo.TipoVeiculo</td>
                <td>@m.Valor.ToString("c")</td>
                <td>@m.TipoEntrega</td>
                <td>@m.FormaDePagamento.ModeloFormaDePagamento</td>
                <td>@m.Observacoes</td>
            </tr>
        }
    </tbody>
</table>

VendaDeAutomoveis/Views/Venda/Index.cshtml
@model IList<VendaDeAutomoveis.Entidades.Venda>

<br />
<br />
<br />
<br />

<table class="table table-hover">
    <thead>
        <tr id="trs"> 
            <th>Nome do Cliente</th>
            <th>Veículo</th>
            <th>Valor da Comrpa</th>
            <th>Data da Compra</th>
            <th>Entrega</th>
            <th>Forma de Pagamento</th>
            <th>Observação</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var m in Model)
        {
            <tr>
                
                <td>@m.Cliente.Nome</td>
                <td>@m.Veiculo.ModeloVeiculo</td>
                <td>@m.Valor.ToString("c")</td>
                <td>@m.DataCompra.ToString("dd/MM/yyyy")</td>
                <td>@m.TipoEntrega</td>
                <td>@m.FormaDePagamento.ModeloFormaDePagamento</td>            
                <td>@m.Observacoes</td>
            </tr>
        }
    </tbody>
</table>

<style>
    #trs th{
        width: 120px;
    }
</style>

VendaDeAutomoveis/Views/Venda/_ParcialViewFormaDePagamento.cshtml
@model IList<VendaDeAutomoveis.Entidades.FormaDePagamento>

@using (Html.BeginForm("AdicionarVenda", "Venda", FormMethod.Post))
{
    
    @Html.Label("Forma de Pagamento")
    @Html.DropDownList("IdFormaDePagamento",
                new SelectList(Model, "IdFormaDePagamento", "ModeloFormaDePagamento"), "Forma de Pagamento",
        new { @class = "form-control" })
    @Html.ValidationMessage("FormaDePagamentoModel")

}


VendaDeAutomoveis/Views/Venda/_ParcialviewEndereco.cshtml
@model VendaDeAutomoveis.Entidades.Cliente

@using (Html.BeginForm("AdicionarCliente", "Cliente", FormMethod.Post))
{
    <br />
    
    @Html.HiddenFor(u => u.IdCliente, new { @class = "form-control" })
    
    @Html.LabelFor(u => u.Endereco, "Endereço*")
    @Html.TextBoxFor(u => u.Endereco, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.Endereco)

    <br />

    @Html.LabelFor(u => u.NumeroDaCasa, "Número da casa*")
    @Html.TextBoxFor(u => u.NumeroDaCasa, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.NumeroDaCasa)

    <br />

    @Html.LabelFor(u => u.Complemento, "Complemento*")
    @Html.TextBoxFor(u => u.Complemento, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.Complemento)

    <br />

    @Html.LabelFor(u => u.CEP, "CEP*")
    @Html.TextBoxFor(u => u.CEP, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.CEP)

    <br />

    @Html.LabelFor(u => u.Bairro, "Bairro*")
    @Html.TextBoxFor(u => u.Bairro, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.Bairro)

    <br />

    @Html.LabelFor(u => u.Cidade, "Cidade*")
    @Html.TextBoxFor(u => u.Cidade, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.Cidade)

    <br />

    @Html.LabelFor(u => u.Estado, "Estado*")
    @Html.TextBoxFor(u => u.Estado, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.Estado)

    <br />
    
    <input id="atualizar" type="button" value="atualizar" />
    
    @section Scripts {

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.maskedinput.min.js"></script>


    }
  
}
