VendaDeAutomoveis/Controllers/VeiculoController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Web;
using System.Web.Mvc;
using VendaDeAutomoveis.Entidades;
using VendaDeAutomoveis.Factory.Base.Upload;
using VendaDeAutomoveis.Filters;
using VendaDeAutomoveis.Repository;

namespace VendaDeAutomoveis.Controllers
{
    [AutorizacaoFilter]
    public class VeiculoController : Controller
    {
        private VeiculoRepository veiculoRepository;

        public VeiculoController(VeiculoRepository veiculoRepository)
        {
            this.veiculoRepository = veiculoRepository;
        }

        public ActionResult FormularioCadastro()
        {
            return View();
        }

        public ActionResult AdicionarProduto(Veiculo veiculo)
        {
            foreach (string nomeArquivo in Request.Files)
            {
                HttpPostedFileBase file = Request.Files[nomeArquivo];
                UploadArquivoFactory.Upload(file, nomeArquivo);
            }

            veiculo.IdUpload = 1;
            if (ModelState.IsValid)
            {
                veiculoRepository.Adicionar(veiculo);
                return RedirectToAction("Index");
            }
            else
            {
                return View("FormularioCadastro", veiculo);
            }
        }

        public ActionResult EditarProduto(Guid id)
        {
            var veiculo = veiculoRepository.ObterPorId(id);
            return View(veiculo);
        }

        public ActionResult EditarProdutos(Veiculo veiculo)
        {
            if (ModelState.IsValid)
            {
                veiculoRepository.Editar(veiculo);
                return RedirectToAction("Index");
            }
            else
            {
                return View("EditarProduto", veiculo);
            }
        }

        public ActionResult Excluir(Guid id)
        {
            veiculoRepository.Excluir(id);
            return RedirectToAction("Index");
        }

        public ActionResult Index()
        {
            IList<Veiculo> veiculos = veiculoRepository.ObterTodos();

            return View(veiculos);
        }

        public ActionResult Teste()
        {
            return View();
        }

        public ActionResult VerImagem()
        {
            //Adicione quantas extensões você desejar!
            //List<String> oListTiposImagens = new List<string>();
            //oListTiposImagens.Add("*.gif");
            //oListTiposImagens.Add("*.png");
            //oListTiposImagens.Add("*.jpg");

            //var ImagemNome = uploadArquivoDAO.pegarNomeImagemPorIdProduto(idProduto);

            var nomecompleto = System.IO.Path.Combine(ConfigurationManager.AppSettings["caminhoRepositorioDeArmazenamento"], "uno" + ".png");

            var arquivoInfo = new FileInfo(nomecompleto);

            //string[] imagens2 = Directory.GetFiles(caminhoDiretorio, "*.png");

            return base.File(nomecompleto, "uno.png");
        }

        public ActionResult SalvarArquivo()
        {
            var fazerUpload = false;

            foreach (string nomeArquivo in Request.Files)
            {
                HttpPostedFileBase file = Request.Files[nomeArquivo];
                fazerUpload = UploadArquivoFactory.Upload(file, nomeArquivo);
            }

            if (fazerUpload)
                return Content("ok");
            else
                return Content("Erro");

            //var caminhoDiretorio = ConfigurationManager.AppSettings["caminhoRepositorioDeArmazenamento"].ToString();//Config fora do sistema (Web config)

            //string nomeA = string.Empty;

            //Guid arquivoGuid;
            //arquivoGuid = Guid.NewGuid();
            //try
            //{
            //    foreach (string nomeArquivo in Request.Files)
            //    {
            //        HttpPostedFileBase file = Request.Files[nomeArquivo];
            //        nomeA = file.FileName;
            //        if (file != null && file.ContentLength > 0)
            //        {
            //            var nomeArquivoCarregado = Path.GetFileName(file.FileName);

            //            bool existenciaDiretorio = System.IO.Directory.Exists(caminhoDiretorio);
            //            if (!existenciaDiretorio)
            //            {
            //                System.IO.Directory.CreateDirectory(caminhoDiretorio);
            //            }
            //            var caminhoArquivo = string.Empty;
            //            var extensao = System.IO.Path.GetExtension(nomeA);

            //            caminhoArquivo = string.Format("{0}\\{1}", caminhoDiretorio, arquivoGuid + ".png");

            //            file.SaveAs(caminhoArquivo);

            //            string recebendoDetalhes = arquivo.Detalhes;

            //            arquivo.Detalhes = "<br/>" + "<ol/>" + " - " + nomeArquivoCarregado + recebendoDetalhes;
            //        }

            //        arquivo.Data = DateTime.Now;

            //        //uploadArquivoDAO.AdicionarArquivo(arquivo);
            //    }
            //    return Content("Ok");
            //}
            //catch (Exception ex)
            //{
            //    return Json(new { Message = "Erro em Salvar o Arquivo" });
            //}
        }
    }
}

VendaDeAutomoveis/Views/Veiculo/EditarProduto.cshtml
@model VendaDeAutomoveis.Entidades.Veiculo

<br />
<br />
<br />
<br />

@using (Html.BeginForm("EditarProdutos", "Produto", FormMethod.Post))
{
    @*@Html.LabelFor(u => u.IdProduto, "Id produto*")*@
    @Html.HiddenFor(u => u.Id, new { @class = "form-control" })

    @Html.LabelFor(u => u.Fabricante, "Nome do fabricante*")
    @Html.TextBoxFor(u => u.Fabricante, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.Fabricante)

    <br />

    @Html.LabelFor(u => u.ModeloVeiculo, "Modelo do veículo*")
    @Html.TextBoxFor(u => u.ModeloVeiculo, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.ModeloVeiculo)

    <br />

    @Html.LabelFor(u => u.Ano, "Ano de Fabricação do veículo*")
    @Html.TextBoxFor(u => u.Ano, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.Ano)

    <br />


    @Html.LabelFor(u => u.QuantidadeDePortas, "Quantidade de portas do veículo*")
    @Html.TextBoxFor(u => u.QuantidadeDePortas, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.QuantidadeDePortas)

    <br />

    @Html.LabelFor(u => u.Valor, "Valor do veículo*")
    @Html.TextBoxFor(u => u.Valor, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.Valor)

    <br />

    @Html.LabelFor(u => u.TipoVeiculo, "Tipo do veículo*")
    @Html.EnumDropDownListFor(u => u.TipoVeiculo, "Tipo do veiculo", new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.TipoVeiculo)

    <br />

    <input type="submit" value="Salvar" />

}

VendaDeAutomoveis/Views/Veiculo/FormularioCadastro.cshtml
@model VendaDeAutomoveis.Entidades.Veiculo

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/fileinput.js"></script>
<link href="~/Content/bootstrap-fileinput/css/fileinput.css" rel="stylesheet" />
<link href="~/Content/bootstrap-fileinput/css/fileinput.min.css" rel="stylesheet" />

<br />
<br />
<br />
<br />

@using (Html.BeginForm("AdicionarProduto", "Veiculo", FormMethod.Post))
{
    @Html.LabelFor(u => u.Fabricante, "Nome do fabricante*")
    @Html.TextBoxFor(u => u.Fabricante, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.Fabricante)

    <br />

    @Html.LabelFor(u => u.ModeloVeiculo, "Modelo do veículo*")
    @Html.TextBoxFor(u => u.ModeloVeiculo, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.ModeloVeiculo)

    @*<br />

    @Html.LabelFor(u => u.Ano, "Ano de Fabricação do veículo*")
    @Html.TextBoxFor(u => u.Ano, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.Ano)*@

    <br />

    @Html.LabelFor(u => u.QuantidadeDePortas, "Quantidade de portas do veículo*")
    @Html.TextBoxFor(u => u.QuantidadeDePortas, new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.QuantidadeDePortas)

    <br />

    @Html.LabelFor(u => u.Valor, "Valor do veículo*")
    @Html.TextBoxFor(u => u.Valor, new { @id = "preco", @class = "form-control" })
    @Html.ValidationMessageFor(u => u.Valor)

    <br />

    @Html.LabelFor(u => u.TipoVeiculo, "Tipo do veículo*")
    @Html.EnumDropDownListFor(u => u.TipoVeiculo, "Tipo do veiculo", new { @class = "form-control" })
    @Html.ValidationMessageFor(u => u.TipoVeiculo)

    <br />

    <input type="submit" class="btn-success" value="Cadastrar" />
}
<br />

<form id="formUploadArquivo" action="@Url.Action("SalvarArquivo", "Produto")" method="post" enctype="multipart/form-data">
    <label class="control-label">Selecione a imagem do veículo</label>
    <input type="file" name="file" class="file">
</form>


@section scripts{
    <script type="text/javascript">
        $(function () {
            $("#input-id").fileinput();

            // with plugin options
            $("#input-id").fileinput({ 'showUpload': false, 'previewFileType': 'any' });
        });

        $('.btn btn-default fileinput-upload fileinput-upload-button').click(function () {
            $('#formUploadArquivo').submit();
        });
       
    </script>
}


VendaDeAutomoveis/Views/Veiculo/Index.cshtml
@model IList<VendaDeAutomoveis.Entidades.Veiculo>

<br />
<br />
<br />
<br />

<table class="table table-hover">
    <thead>
        <tr>
            
            <th>Nome do fabricante</th>
            <th>Modelo do veículo</th>
            <th>Ano de Fabricação do veículo</th>
            <th>Valor do veículo</th>
            <th>Tipo do veículo</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var u in Model)
        {
            <tr>
               
                <td>@u.Fabricante</td>
                <td>@u.ModeloVeiculo</td>
                <td>@u.Ano</td>
                <td>@u.Valor</td>
                <td>@u.TipoVeiculo </td>
                <td>@Html.ActionLink("Editar", "EditarProduto", new { idProduto = u.Id }, new { @class = "btn-success" })</td>
                <td>@Html.ActionLink("Excluir", "Excluir", new { idProduto = u.Id }, new { @class = "bg-warning" })</td>
            </tr>
        }
    </tbody>
</table>

VendaDeAutomoveis/Views/Veiculo/VerImagem.cshtml

@{
    ViewBag.Title = "VerImagem";
}

<h2>VerImagem</h2>


VendaDeAutomoveis/Views/Veiculo/_CadastroUpload.cshtml
@model VendaDeAutomoveis.Entidades.Upload

<br />
<br />

@Html.LabelFor(u => u.Cliente, "Adicionar")
@Html.TextBoxFor(u => u.Cliente, new { @class = "form-control" })
@Html.ValidationMessageFor(u => u.Cliente)
<br />
<br />
@Html.LabelFor(u => u.NomeArquivo, "Adicionar")
@Html.TextBoxFor(u => u.NomeArquivo, new { @class = "form-control" })
@Html.ValidationMessageFor(u => u.NomeArquivo)